version: '3'

services:
  backend:
    build:
      context: ./boilerplate-backend
    ports:
      - "8000:8000"
    volumes:
      - ./boilerplate-backend:/code
    environment:
      - DEBUG=1
      - SECRET_KEY=your_secret_key
    depends_on:
      - db
  frontend:
    build:
      context: ./boilerplate-frontend
    ports:
      - "8080:8080"
    volumes:
      - ./boilerplate-frontend:/app
    depends_on:
      - backend

  # db:
  #   image: postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: boilerplate_db
